### ISSUE TITLE
Python: Scale up to process entire layer

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_shared_streets_conflator#10]
Convert the following code into functions and allow it to run in a loop until the layer is processed:
- [ ] Pull input data from DB
- [ ] Sending input to SharedStreets API
- [ ] Return SharedStreets data to the DB

Use the "default" parameters you've determined for the centreline or whatever layer.

**Comment by chmnata** [comment]
We tried the centreline layer with `FCODE_DESC IN ('Collector','Collector Ramp',
    'Local','Major Arterial','Major Arterial Ramp','Minor Arterial',
    'Minor Arterial Ramp','Pending')`

reference table in `natalie.test_table`

- 2182/67796 rows unmatched (3.2%)
- lots of local streets not getting matched (`tilehierarchy`???)
- medians streets only have one side of street showing up (need to create geometry for both direction)
- some reference came back having a section value like this `'section': [101.86488640123036, 101.84]`, which appears to be points that got matched in intersections (but shouldn't happen since length tolerance is at 0.6). For these cases, we altered the value for section to `empty`. 

Example of a match with an  `empty` section:
![image](https://user-images.githubusercontent.com/46324452/54692301-2afd4980-4afb-11e9-8a48-6e8e5a0baa2f.png)

**Comment by chmnata** [comment]
To improve matching on median streets, we duplicated the streets thats non-one way and fix the direction of all streets. (`gis_shared_shreets.centreline_both_dir)

- 1689/132378 rows unmatched (1.3%)
- `empty` section increased from 5 to 12
-

**Comment by chmnata** [comment]
We downloaded `gis.centreline_one_way` from open data catalogue and transformed it into a layer that contain one line for each direction (`gis_shared_streets.centreline_both_dir`) using the following query:
```
create table gis_shared_streets.centreline_both_dir as (with temp as (select geo_id, fcode_desc, case when one_way_di = '-1' then ST_reverse(geom) else geom end as dir_geom
from gis.centreline_one_way
where one_way_di = '-1' or one_way_di = '1'

union all

select geo_id,fcode_desc,  case when one_way_di = '0' then ST_reverse(geom) end as dir_geom
from gis.centreline_one_way
where one_way_di = '0'

union all

select geo_id, fcode_desc, geom as dir_geom
from gis.centreline_one_way
where one_way_di = '0')

, tempa2 as (select geo_id, fcode_desc, gis.direction_from_line(dir_geom)as direction, dir_geom
from temp
order by geo_id)

select geo_id, fcode_desc, 'direction' || (row_number() over (partition by geo_id order by geo_id))::text as direction , dir_geom
from tempa2
where direction is null

union all

select geo_id, fcode_desc, direction, dir_geom
from tempa2
where direction is not null )
```
