### ISSUE TITLE
tileHierarchy=8 run into 504 error

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_shared_streets_conflator#15]
Previously we documented that using `tileHierarchy=8` on bluetooth segments will result in a 504 error from sharedstreets API. However, running `tileHierarchy=8` on some HERE segments also resulted in a 504 error in a recent attempt to conflate HERE data. 

`tileHierarchy=8` can be useful for finely detailed datasets such as HERE (and possibly centreline) where it includes driveways and other "finer" road classes. 

![image](https://user-images.githubusercontent.com/46324452/55639008-7029a880-5796-11e9-8adc-81ad8ca72d7a.png)

Sample original HERE segment that returned with a 504 error:
[Original GeoJSON](https://gist.githubusercontent.com/chmnata/68c9615d4df8914dddb209e0ba89dd8f/raw/dd411fa75d9bc151531fd5d6e01dca3ebe1f1128/unmatched_here)

Parameters used:
- bearingtolerance = 25
- lengthtolerance = 0.6
- ignoreDirection=false
- searchradius = 60
- tilehierarchy = 8 
- planet = 181029

**Comment by emilyeros** [comment]
This is a timeout problem. I get this same error if I use your sample dataset of 300 features, but not if I trim it down to fewer features. Here's a [test set of the first 75 features](https://gist.githubusercontent.com/emilyeros/43e0e12bc192b1aee16a9d11ac1f06bc/raw/e0b2d6f01b59b2d7657d76f9a9976ae74b7736cd/toronto504.geojson). This conflated successfully using the API.

In the short term, you could change your Python pinger so that it iterates through a smaller set of features at a time (Instead of iterating through 300 features at a time, try 100). 

In the medium term (next couple of weeks), we can get you set up with the CLI - we've got it running but we're still adding options for all the input parameters. It does not face the same timeout issues. Once you're up and running with the CLI, you'll be able to easily handle larger datasets and higher tiler hierarchies.
