### ISSUE TITLE
Tune parameters.

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_shared_streets_conflator#9]
Automate optimizing parameters to match a layer

**Comment by chmnata** [comment]
To help keep track of which parameters we used, how many rows were matched using those parameters, as well as the number of time the function was run, we created `query_info_table` as an output table to store those information. We chose to create a separate table in order to reduce storage because storing all the information in the output table would take up too much space. We added the column `query_num` in the output table as a foreign key. 
*The ideal structure of a query_info_table is `gis_shared_streets.query_info_structure`*
